### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by saul-data** [CoreDB-io/coredb#16]
Hi there, I love the concept of this. I tend to find I need to a database that is close to my code, preferably even embedded and synced across the Kubernetes pods for performance. In my case we use Golang and I have many cases where I need to be able to select using secondary indexes. Its hard to find a postgresql compatible or embedded database that is capable of doing that.

**Comment by sjmiller609** [comment]
@saul-data can you give more information about your use case? I am doing user research for a possible feature for user-hosted read replicas.
