### ISSUE TITLE
What is the applicable scenario of pgmq?

### ISSUE THREAD

**Issue by l-7-l** [CoreDB-io/coredb#298]
>I am an independent developer with no experience in backend development. Considering the complexity and 'waste' of microservices/kubernetes/kafka, I decided to adopt the event-driven Monolith architecture. I have the following questions about pgmq. Any suggestions will be very helpful gratitude

Is it production ready?
Is it suitable for e-commerce? 
Can the order of consumption be guaranteed? 
Does it support multiple consumers?

**Comment by ChuckHend** [comment]
👋 @l-7-l 

> Is it production ready?

Yes it is production ready and we are using pgmq at CoreDB in our managed service. 

> Can the order of consumption be guaranteed?

Yes, order is FIFO by default.

> Does it support multiple consumers?

Yes! You can have many consumers concurrently reading from the same queue and messages are delivered to exactly one consumer within the visibility timeout parameter you specify.

**Comment by l-7-l** [comment]
thankyou
